Fix reconnect issues
ElrondNetwork/notifier-go pull request #37
Opened 2022-04-08 05:42 UTC by ssd04

2022-04-08 13:53 UTC, sstanculeanu submitted a review, later dismissed

2022-04-11 12:31 UTC, AdoAdoAdo requested changes

2022-04-11 12:31 UTC, AdoAdoAdo commented on rabbitmq/rabbitClient.go
> +	arkCh     chan uint64
ack, nack?

2022-04-11 12:31 UTC, AdoAdoAdo commented on rabbitmq/rabbitClient.go
> +	narkCh    chan uint64
can we remove the nack channel?
if there is no special treatment

2022-04-11 12:31 UTC, AdoAdoAdo commented on rabbitmq/rabbitClient.go
> +			log.Debug("Publish: published message ack")
can we do a return here instead of multiple continues on the other cases and a break?

2022-04-11 12:51 UTC, AdoAdoAdo approved these changes

2022-04-11 12:53 UTC, sstanculeanu approved these changes

2022-04-11 12:54 UTC, merged